USE [master]
GO

-- [H1172566] >> [PwhcProd01]

--/home/cftc/mssqlLatest/ | PwhcProd01
/****** Object:  Database PwhcProd01    Script Date: 1/31/2019 4:21:05 AM ******/
CREATE DATABASE PwhcProd01
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PWHCProd01_Data', FILENAME = N'/home/cftc/mssqlLatest/H1172566.mdf' , SIZE = 63189696KB , MAXSIZE = UNLIMITED, FILEGROWTH = 204800KB ), 
 FILEGROUP [H1172566_FG] CONTAINS FILESTREAM  DEFAULT
( NAME = N'H1172566_FG', FILENAME = N'/fs/H1172566_FS' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'PWHCProd01_Log', FILENAME = N'/home/cftc/mssqlLatest/H1172566.ldf' , SIZE = 152576512KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024000KB )
GO

ALTER DATABASE PwhcProd01 SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC PwhcProd01.[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE PwhcProd01 SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE PwhcProd01 SET ANSI_NULLS OFF 
GO

ALTER DATABASE PwhcProd01 SET ANSI_PADDING OFF 
GO

ALTER DATABASE PwhcProd01 SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE PwhcProd01 SET ARITHABORT OFF 
GO

ALTER DATABASE PwhcProd01 SET AUTO_CLOSE OFF 
GO

ALTER DATABASE PwhcProd01 SET AUTO_SHRINK OFF 
GO

ALTER DATABASE PwhcProd01 SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE PwhcProd01 SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE PwhcProd01 SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE PwhcProd01 SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE PwhcProd01 SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE PwhcProd01 SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE PwhcProd01 SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE PwhcProd01 SET  DISABLE_BROKER 
GO

ALTER DATABASE PwhcProd01 SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE PwhcProd01 SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE PwhcProd01 SET TRUSTWORTHY OFF 
GO

ALTER DATABASE PwhcProd01 SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE PwhcProd01 SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE PwhcProd01 SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE PwhcProd01 SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE PwhcProd01 SET RECOVERY FULL 
GO

ALTER DATABASE PwhcProd01 SET  MULTI_USER 
GO

ALTER DATABASE PwhcProd01 SET PAGE_VERIFY NONE  
GO

ALTER DATABASE PwhcProd01 SET DB_CHAINING OFF 
GO

ALTER DATABASE PwhcProd01 SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE PwhcProd01 SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE PwhcProd01 SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE PwhcProd01 SET QUERY_STORE = OFF
GO

USE PwhcProd01
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE PwhcProd01 SET  READ_WRITE 
GO


